force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <label>Medical Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Status__c</fullName>
    <label>Appointment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming</fullName>
                <default>true</default>
                <label>Upcoming</label>
            </value>
            <value>
                <fullName>Made</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>&quot;Doctor&quot;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>&quot;Patient&quot;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Patient)</relationshipLabel>
    <relationshipName>Medical_Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/recordTypes/Online.recordType-meta.xml
<RecordType>
    <fullName>Online</fullName>
    <active>true</active>
    <label>Online</label>
</RecordType>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Person Surname</description>
    <label>Last Name</label>
    <length>51</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Laryngologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Person__c/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <label>Patient</label>
</RecordType>

force-app/main/default/classes/AppointmentController.cls
public with sharing class AppointmentController {
    
    @AuraEnabled(cacheable = true)
    public static List<Medical_Facility__c> getAllFacilities() {
        return 
            [
                select Id, Name from Medical_Facility__c 
                with SECURITY_ENFORCED
            ];
    }

    @AuraEnabled(cacheable = true)
    public static List<AggregateResult> getAllSpecializationsFromDoctorsWorkingInAFacility(String facilityId) {
        return 
            [
                select Specialization__c from Person__c 
                where RecordType.Name = 'Doctor'
                and Medical_Facility__c =: facilityId
                with SECURITY_ENFORCED
                group by Specialization__c
            ];
    }

    @AuraEnabled(cacheable = true)
    public static List<Person__c> getAllDoctorsWorkingInCurrentFacility(String facilityId, String specialization) {
        return new List<Person__c>(
            [
                select Id, Name, Last_Name__c from Person__c 
                where RecordType.Name = 'Doctor'
                and Medical_Facility__c =: facilityId
                and Specialization__c =: specialization
                with SECURITY_ENFORCED
            ]
        );
    }

    @AuraEnabled
    public static void saveAppointment(
            String facilityId, String doctorId, String patientId, String isOnline, String dateTimeString
        ) {
        Id recordId = isOnline == 'Online' ? 
        AppointmentController.getRecordTypeIdbyName('Medical_Appointment__c', 'Online')
        : AppointmentController.getRecordTypeIdbyName('Medical_Appointment__c', 'On Site');
        
        AggregateResult name = [select count(Patient__c) from Medical_Appointment__c where Medical_Facility__c =: facilityId and Patient__c =: patientId];
        System.debug('recordId: ' + recordId + ' doctor: ' + doctorId + ' patient: ' + patientId + ' isonline: ' + isOnline + ' date: ' + dateTimeString);

        Medical_Appointment__c appointment = new Medical_Appointment__c(
            Name=String.valueOf((Integer)name.get('expr0')) + ' visit', 
            Doctor__c=doctorId, 
            Medical_Facility__c=facilityId, 
            Patient__c=patientId, 
            Appointment_Status__c='Upcoming', 
            Appointment_Date__c = DateTime.valueOf(dateTimeString.replace('T', ' ')),
            RecordTypeId = recordId
        );

        insert appointment;
    }
    public static Id getRecordTypeIdbyName(String objectName, String strRecordTypeName){
        return  Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosByName().get(strRecordTypeName).getRecordTypeId();
    }
}



//     @AuraEnabled
// public static void saveAppointment(
//     String facilityId, String doctorId, String patientId, String isOnline, String dateTimeString
// ) {
//     String recordTypeName = (isOnline == 'Online') ? 'Online' : 'On-Site';

//     Schema.DescribeSObjectResult describeResult = Medical_Appointment__c.sObjectType.getDescribe();
//     System.debug(describeResult);
//     Map<String, Schema.RecordTypeInfo> recordTypeInfosByName = describeResult.getRecordTypeInfosByName();

//     if (recordTypeInfosByName != null && recordTypeInfosByName.containsKey(recordTypeName)) {
//         Id recordId = recordTypeInfosByName.get(recordTypeName).getRecordTypeId();
//         System.debug('recordId: ' + recordId + ' doctor: ' + doctorId + ' patient: ' + patientId + ' isonline: ' + isOnline + ' date: ' + dateTimeString);

//         Medical_Appointment__c appointment = new Medical_Appointment__c(
//             Name='test visit', 
//             Doctor__c=doctorId, 
//             Medical_Facility__c=facilityId, 
//             Patient__c=patientId, 
//             Appointment_Status__c='Upcoming', 
//             Appointment_Date__c = DateTime.valueOf(dateTimeString.replace('T', ' ')),
//             RecordTypeId = recordId
//         );

//         insert appointment;
//     } else {
//         // Handle the case where the record type info is not available
//         System.debug('Record type info not found for: ' + recordTypeName);
//     }
// }

// }