force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <label>Medical Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Id__c</fullName>
    <label>Appointment Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Status__c</fullName>
    <label>Appointment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming</fullName>
                <default>true</default>
                <label>Upcoming</label>
            </value>
            <value>
                <fullName>Made</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>&quot;Doctor&quot;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>&quot;Patient&quot;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Patient)</relationshipLabel>
    <relationshipName>Medical_Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/recordTypes/Online.recordType-meta.xml
<RecordType>
    <fullName>Online</fullName>
    <active>true</active>
    <label>Online</label>
</RecordType>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Person Surname</description>
    <label>Last Name</label>
    <length>51</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Laryngologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <label>Patient</label>
</RecordType>

force-app/main/default/classes/MedicalAppointmentTriggerHandler.cls
public with sharing class MedicalAppointmentTriggerHandler {
  public void sendAppointmentEmail(
    List<Medical_Appointment__c> triggerNew,
    Map<Id, Medical_Appointment__c> oldMap
  ) {
    Map<Id, List<Medical_Appointment__c>> patientAppointments = new Map<Id, List<Medical_Appointment__c>>();
    for (Medical_Appointment__c appointment : triggerNew) {
      if (oldMap != null) {
        Medical_Appointment__c old = oldMap.get(appointment.Id);
        if (
          old.Name == appointment.Name &&
          old.Appointment_Date__c.format() ==
          appointment.Appointment_Date__c.format() &&
          old.Appointment_Status__c == appointment.Appointment_Status__c &&
          old.Doctor__c == appointment.Doctor__c &&
          old.Patient__c == appointment.Patient__c &&
          old.recordTypeId == appointment.recordTypeId &&
          old.Medical_Facility__c == appointment.Medical_Facility__c
        ) {
          continue;
        }
      }
      if (!patientAppointments.containsKey(appointment.Patient__c)) {
        patientAppointments.put(
          appointment.Patient__c,
          new List<Medical_Appointment__c>{ appointment }
        );
      } else {
        patientAppointments.get(appointment.Patient__c).add(appointment);
      }
    }

    List<Person__c> patients = [
      SELECT Id, Name, Last_Name__c, Email__c
      FROM Person__c
      WHERE Id IN :patientAppointments.keySet()
    ];

    List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
    for (Person__c patient : patients) {
      for (
        Medical_Appointment__c appointment : patientAppointments.get(patient.Id)
      ) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new List<String>{ patient.Email__c });
        mail.setSubject('Updated Appointment Information!');

        String template = 'Dear {0} {1},\n\nYour Medical Appointment has been updated!\nDetails from the visit:\n\tMedical Appointment Name: {2}\n\tPatient: {3} {4}\n\tAppointment Date: {5}\n\tAppointment Status: {6}\n\tAppointment ID: {7}\n\nIf something is not correct, please contact us!\nHealth Care App Team';
        List<Object> parameters = new List<Object>{
          patient.Name,
          patient.Last_Name__c,
          appointment.Name,
          patient.Name,
          patient.Last_Name__c,
          appointment.Appointment_Date__c.format(),
          appointment.Appointment_Status__c,
          appointment.Appointment_Id__c
        };
        String formatted = String.format(template, parameters);

        mail.setPlainTextBody(formatted);
        emailsToSend.add(mail);
      }
    }
    Messaging.sendEmail(emailsToSend);
  }

  public void firstVisitToAnInternistOnSite(
    List<Medical_Appointment__c> triggerNew
  ) {
    Id recType = Medical_Appointment__c.getSObjectType()
      .getDescribe()
      .getRecordTypeInfosByName()
      .get('Online')
      .getRecordTypeId();
    List<Id> doctors = new List<Id>();
    for (Medical_Appointment__c appointment : triggerNew) {
      doctors.add(appointment.Doctor__c);
    }

    List<Id> internistsIds = new List<Id>();
    List<Person__c> internists = [
      SELECT Id
      FROM Person__c
      WHERE Specialization__c = 'Internist' AND Id IN :doctors
    ];
    for (Person__c internist : internists) {
      internistsIds.add(internist.Id);
    }

    List<Medical_Appointment__c> appointments = new List<Medical_Appointment__c>();
    List<Id> patients = new List<Id>();
    for (Medical_Appointment__c appointment : triggerNew) {
      if (
        appointment.RecordTypeId == recType &&
        internistsIds.contains(appointment.Doctor__c)
      ) {
        appointments.add(appointment);
        patients.add(appointment.Patient__c);
      }
    }

    List<Id> patientsIds = new List<Id>();
    List<AggregateResult> appointmentsWithInternists = [
      SELECT COUNT(Id), Patient__c
      FROM Medical_Appointment__c
      WHERE
        Doctor__r.Specialization__c = 'Internist'
        AND Patient__c IN :patients
        AND RecordTypeId != :recType
      GROUP BY Patient__c
    ];

    for (AggregateResult ar : appointmentsWithInternists) {
      patientsIds.add(ar.get('Patient__c').toString());
    }

    for (Medical_Appointment__c appointment : appointments) {
      if (!patientsIds.contains(appointment.Patient__c)) {
        appointment.addError('First visit in Internist must be On Site');
      }
    }
  }
}