force-app/main/default/objects/Medical_Facility__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EinsteinClasses/EinsteinApexClassesGettingAllNames.cls
global class EinsteinApexClassesGettingAllNames {
    @InvocableMethod(label='Get All Cities')
    global static List<String> getAllFacilities() {
        List<AggregateResult> citiesNames = [select City__c from Medical_Facility__c group by City__c];
        List<String> cities = new List<String>();

        for (AggregateResult city : citiesNames) {
            cities.add(String.valueOf(city.get('City__c')));
        }

        return cities;
    }
}